services:
  postgres:
    image: postgres:18-alpine
    container_name: aux_system_uatf_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aux_system_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  workspace:
    image: node:24-alpine
    container_name: aux_system_workspace
    working_dir: /app
    command: sh -c "corepack enable && corepack prepare pnpm@10.33.0 --activate && pnpm install && pnpm dev"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/aux_system_db
      CI: "true"
    depends_on:
      - postgres

volumes:
  postgres_data: