FROM node:24-alpine AS base
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@10.33.0 --activate

COPY ../../package.json ../../pnpm-lock.yaml ../../pnpm-workspace.yaml ./
COPY ../../apps ./apps

RUN pnpm install --frozen-lockfile

WORKDIR /app/apps/backend-nest
RUN pnpm build

EXPOSE 3001
CMD ["node","dist/main"]